import type { Lang } from "@/lib/language"

const en = {
  brandTag: "Farmer scheme register",
  navRegister: "The register",
  navFinder: "What fits me",
  navSources: "Sources",
  openMenu: "Open menu",
  footerBlurb:
    "An independent register of central and Haryana schemes for Indian farmers. Not a government website. Check the official source before you apply, pay a fee, or share documents.",
  footerBrowse: "Browse the register",
  footerFit: "See what may fit",
  footerSources: "Sources and how to read a scheme",
  footerState: "State schemes on myScheme",
  navSaved: "Saved",
  homeEyebrow: "India · Independent register",
  homeTitle: "Selected farmer schemes, on one desk.",
  homeLead: () =>
    "Find a useful starting point, check who it may suit, and see what to ask before you apply.",
  homeSaveNote: "Save a scheme or return to a page later. Your list stays on this device.",
  homeIllustrationAlt: "Illustration of a farmer, a field, and a village office",
  homeIllustrationTag: "Kisan Patra · field notes",
  homeIllustrationCard: "A clear first step",
  homeIllustrationTitle: "Start with your need",
  homeIllustrationBody: "Eligibility, papers, and official links in one place.",
  homeStartTitle: "Three useful places to begin",
  homeStartNumber: (n: number) => `START ${String(n).padStart(2, "0")}`,
  homeStarterDescription: (index: number, fallback: string) => ["₹6,000 a year in three instalments, subject to land record checks.", "Crop insurance for notified crops. State participation and cut-offs vary.", "Seasonal credit through a bank; interest support has separate conditions."][index] ?? fallback,
  homeStateResume: (name: string) => `See options for ${name}`,
  homeStateOutside: "This register has selected Haryana programmes. For other states, check myScheme.",
  homeReadScheme: "Read this scheme →",
  homeSeasonEyebrow: "Seasonal example · catalogue reviewed 26 September 2026",
  homeSeasonTitle: "Planning for the Rabi 2026–27 season?",
  homeSeasonPanelBody: "PMFBY enrolment cut-offs depend on your state, crop, and season notification. This register does not confirm that enrolment is open; check the current official notice before relying on a date.",
  homeSeasonLink: "Read about crop insurance",
  homeBrowseHint: "A quick route into the register",
  homeHaryanaTitle: "Looking for Haryana programmes?",
  homeHaryanaBody: "Browse selected state programmes for crop registration, horticulture, irrigation, livestock, dairy, and more. Each has its own route and current notice.",
  homeFeaturedEyebrow: "Selected central programmes",
  homeTrustTitle: "An independent register",
  homeTrustBody: "Kisan Patra is not a government website. Confirm eligibility, deadlines, and fees with the official source linked on each page.",
  homeContinueEyebrow: "Pick up where you left off",
  homeContinueTitle: "Continue exploring",
  homeDeviceOnly: "Stored on this device only · no account needed",
  homeSaved: "Saved schemes",
  homeRecent: "Recently viewed",
  homeClearSaved: "Clear saved list",
  savedPageTitle: "Your saved schemes",
  savedPageBody: "Your saved list and recent pages are stored in this browser on this device. They are not synced to an account.",
  savedEmpty: "No saved schemes yet. Open a scheme and choose Save to keep it here.",
  savedRemove: "Remove",
  homeFit: "See what may fit me",
  homeBrowse: "Browse the full register",
  homeStart: "Start with these three",
  homeOwn: "Own land?",
  homeOwnBody:
    "PM-KISAN pays ₹6,000 a year in three instalments, if the land record is in the family name.",
  homeSeason: "Worried about the season?",
  homeSeasonBody:
    "PMFBY caps your premium. Your state has to have opted in, and you must enrol before the cut-off.",
  homeSeed: "Need money for seed?",
  homeSeedBody:
    "A Kisan Credit Card is the loan. Interest relief sits on top of it. Ask the bank for the prompt-repayment date.",
  statMinistry: "schemes in the ministry’s parliamentary list",
  statAllied: "additional central programmes",
  statPlace: "place to read eligibility, papers, and the official link",
  homeByWork: "By the work it supports",
  schemeCount: (count: number) => (count === 1 ? "1 scheme" : `${count} schemes`),
  homeFeatured: "Often the first ones people need",
  homeFeaturedBody:
    "These are the schemes with a personal application and a number you can check. Haryana’s own schemes are in the register. Other states are not loaded yet.",
  searchLabel: "Search schemes",
  searchPlaceholder: "Try PM-KISAN, drip, honey, pension, solar pump",
  searchButton: "Search",
  registerEyebrow: (count: number) => `${count} entries`,
  registerTitle: "The register",
  registerLead:
    "Search by scheme, crop, or need. Each page has the benefit, who can apply, the papers, and the official link.",
  all: "All",
  emptyTitle: "Nothing matches that search.",
  emptyBody:
    "Try a shorter word — Kisan, drip, honey, pension, fish — or clear the category.",
  emptyHaryana:
    "Nothing in the Haryana list matches. Try registration, paddy, cotton, or switch back to All India.",
  clearSearch: "Clear search",
  showing: (count: number, q: string) =>
    `Showing ${count} ${count === 1 ? "scheme" : "schemes"}${q ? ` for “${q}”` : ""}.`,
  listMinistry: "Ministry list",
  listAllied: "Additional central programme",
  listPlatform: "Trading platform",
  crumbRegister: "Register",
  openOfficial: (label: string) => `Open ${label}`,
  catalogueReview: (date: string) => `Catalogue entry updated ${date}.`,
  sourceVerified: (date: string) => `Source last checked ${date}.`,
  sourceNotVerified: "Source verification is not recorded in this register.",
  whatYouGet: "What you get",
  whoCanApply: "Who can apply",
  papers: "Papers to keep ready",
  howToApply: "How to apply",
  beforePay: "Before you pay anyone",
  rateNote:
    "Rates, crops, and state participation change. The official page is the one that counts.",
  nearby: "Nearby in the register",
  listNote: {
    "ministry-2026":
      "Named in the Ministry of Agriculture & Farmers Welfare list tabled in the Lok Sabha on 3 February 2026.",
    allied:
      "Additional central programme outside that February 2026 annexure.",
    platform:
      "The trading platform inside the Integrated Scheme for Agricultural Marketing. Listed on its own because farmers search for it by name.",
    state:
      "A Haryana government programme. Check its official source for current terms and application dates.",
  },
  finderEyebrow: "A shortlist, not a sanction",
  finderTitle: "Which schemes may fit your farm?",
  finderLead:
    "Start with your state and the work you do. Land and age are optional details that can narrow the list. This is only a shortlist; check eligibility and dates in the official notice.",
  stateLabel: "State or Union Territory",
  statePlaceholder: "Choose a state",
  notSure: "Not sure",
  land: "Land",
  landOwner: "I own cultivable land",
  landTenant: "I farm land I do not own",
  landNone: "I do not cultivate a field",
  landUnsure: "I am not sure about the land record",
  holding: "Holding size",
  holdingSmall: "2 hectares or less",
  holdingLarger: "More than 2 hectares",
  holdingUnsure: "I do not know the area",
  age: "Age",
  ageUnder: "Under 18",
  ageYoung: "18 to 40",
  ageMid: "41 to 59",
  ageOld: "60 or older",
  shg: "I am a woman in a self-help group, or our SHG is looking for a scheme.",
  work: "What do you work on?",
  workHint: "Leave this blank to see the schemes most farm families start with.",
  showSchemes: "Show schemes",
  shortlistTitle: "Your shortlist will land here.",
  shortlistBody:
    "Answer the questions and press show schemes. You will get three piles: apply yourself, apply as a group, and ask the state office.",
  noneTitle: "Nothing in the register matched.",
  noneBody:
    "That can happen if the only schemes for this work are limited to another state, or if land ownership rules you out. Browse the full register, or change an answer.",
  openRegister: "Open the full register",
  mayFit: (count: number) =>
    `${count} schemes may fit. Read the page before you apply. A match is not an entitlement.`,
  bandApply: "Apply yourself",
  bandApplyEmpty: "No personal application stood out. Look at the group and state piles.",
  bandGroup: "Through a group or a business",
  bandGroupEmpty: "No group scheme matched the work you selected.",
  bandState: "Ask the state agriculture office",
  bandStateEmpty: "No state-run scheme matched.",
  aboutEyebrow: "How to read this register",
  aboutTitle: "Sources",
  aboutLead:
    "A scheme page is a briefing, written so you can walk into a bank or a Common Service Centre knowing what to ask. It is not the guideline, and it is not a promise that you will be paid.",
  primaryPages: "Primary pages",
  links: {
    pib: "Lok Sabha reply, 3 February 2026, listing the agriculture schemes",
    ministry: "Department of Agriculture & Farmers Welfare",
    pmkisan: "PM-KISAN",
    pmfby: "PM Fasal Bima Yojana",
    cabinet: "Cabinet continuation of the interest subvention scheme, 28 May 2025",
    haryana: "Meri Fasal Mera Byora, the Haryana crop register",
    myscheme: "myScheme, for states that are not loaded here yet",
  },
  missingEyebrow: "Missing page",
  missingTitle: "That page is not in the register.",
  missingBody:
    "The scheme may have been renamed, or the address is wrong. Search the register by the name you know.",
  missingBack: "Back to the register",
  reasons: {
    overlap: "It lines up with the work you selected.",
    coreGeneral: "A general scheme, still worth checking alongside the specialist ones.",
    core: "One of the schemes most farm families should look at first.",
    owner: "You own cultivable land, which this scheme asks for.",
    cultivator: "You cultivate a crop, including as a tenant where the scheme allows it.",
    unsureLand: "You were unsure about the land record. Confirm that before you apply.",
    small: "Your holding is within 2 hectares, which this pension requires.",
    age: "Your age is inside the window for joining.",
    ageUncertain: "Your age band overlaps the entry window. Check your exact age before applying.",
    shg: "You are in a women self-help group, which is who this selects.",
    state: (name: string) => `It runs in ${name}.`,
    group: "The money goes to a group or a project, not as a personal instalment.",
    startup: "This is for a business or a processing unit, not a seasonal crop loan.",
    throughState: "The state opens this. There may be no personal form on a national portal.",
    open: "Your answers fit its listed criteria; check the scheme page for the current application window.",
  },
  placeLabel: "Which government",
  placeCentre: "All India",
  placeHaryana: "Haryana",
  placeLead:
    "The register includes central schemes and selected Haryana programmes. Haryana entries cover agriculture, horticulture, livestock, dairy, fisheries, irrigation, and related farmer support. Other states are not loaded yet.",
  haryanaTitle: "Haryana’s own schemes",
  haryanaBody:
    "Haryana programmes use different application routes. Some require Meri Fasal Mera Byora registration; others use department portals, SARAL Haryana, a bank, or a district office. Check each scheme’s current notice and deadline.",
  haryanaLink: "Open Haryana schemes",
  faqs: [
    {
      id: "official",
      q: "Is this a government website?",
      a: "No. Kisan Patra is an independent reading desk. Applications, payments, and corrections happen only on the official portal or at the bank, the mandi, or the district office named on each scheme.",
    },
    {
      id: "list",
      q: "Where does the list come from?",
      a: "The register includes the 28 agriculture schemes in the annexure the Minister of State for Agriculture and Farmers Welfare gave in a written Lok Sabha reply on 3 February 2026 (PIB release PRID 2222801), plus selected programmes from other central departments and Haryana. It is not a complete inventory of every farmer-related programme. e-NAM is called out separately because farmers often search for it by name.",
    },
    {
      id: "states",
      q: "Where are the state schemes?",
      a: "Haryana is the first state in the register. Its selected entries cover crop registration and incentives, horticulture, irrigation, livestock and dairy, fisheries, and crop-loss or accident relief. Each programme has its own eligibility and application route. Other states are not loaded yet; use myScheme and confirm details with the relevant state department because programmes and application windows change.",
    },
    {
      id: "numbers",
      q: "Can I rely on the rupee figures?",
      a: "The well-known ones are tied to a public source: ₹6,000 under PM-KISAN, the PMFBY premium caps, the ₹3,000 PM-KMY pension, the MISS rate as continued for 2025–26, the FPO ceilings in the February 2026 reply, the Namo Drone Didi cap, the AgriSURE corpus, and the PMFME 35% cap. Machine and drip percentages move with guidelines and state top-ups, so those pages tell you to confirm the current rate instead of printing a number that may already be old.",
    },
    {
      id: "miss",
      q: "Why does the loan page say ₹3 lakh if the Budget said ₹5 lakh?",
      a: "Budget 2025–26 announced a higher ceiling under the Modified Interest Subvention Scheme. The Union Cabinet continuation for 2025–26, and the Reserve Bank’s operational circular for that year, kept the interest benefit at ₹3 lakh overall and ₹2 lakh when the loan is only for animals, fish, or bees. Ask the bank which ceiling is on your sanction letter.",
    },
  ],
}

const hi: typeof en = {
  brandTag: "किसान योजना पंजिका",
  navRegister: "पंजिका",
  navFinder: "क्या मेरे काम की है",
  navSources: "स्रोत",
  openMenu: "मेनू खोलें",
  footerBlurb:
    "भारतीय किसानों के लिए केंद्र और हरियाणा की योजनाओं की स्वतंत्र पंजिका। यह सरकारी वेबसाइट नहीं है। आवेदन करने, शुल्क देने या कागज़ साझा करने से पहले आधिकारिक स्रोत देख लें।",
  footerBrowse: "पूरी पंजिका देखें",
  footerFit: "देखें क्या आपके काम की है",
  footerSources: "स्रोत और योजना कैसे पढ़ें",
  footerState: "राज्य की योजनाएँ myScheme पर",
  navSaved: "सहेजी योजनाएँ",
  homeEyebrow: "भारत · स्वतंत्र पंजिका",
  homeTitle: "किसानों की चुनी हुई योजनाएँ, एक ही जगह।",
  homeLead: () =>
    "अपनी ज़रूरत से शुरुआत करें, जानें कि कौन सी योजना काम आ सकती है और आवेदन से पहले क्या पूछना है।",
  homeSaveNote: "योजना सहेजें और बाद में फिर खोलें। आपकी सूची इसी डिवाइस पर रहेगी।",
  homeIllustrationAlt: "किसान, खेत और गाँव के कार्यालय का चित्र",
  homeIllustrationTag: "किसान पत्र · खेत की बातें",
  homeIllustrationCard: "पहला कदम साफ़ रखें",
  homeIllustrationTitle: "अपनी ज़रूरत से शुरू करें",
  homeIllustrationBody: "पात्रता, कागज़ और आधिकारिक लिंक एक जगह।",
  homeStartTitle: "शुरुआत के लिए तीन उपयोगी योजनाएँ",
  homeStartNumber: (n) => `शुरुआत ${n}`,
  homeStarterDescription: (index, fallback) => ["साल में ₹6,000 तीन किस्तों में, ज़मीन के रिकॉर्ड की जाँच के बाद।", "अधिसूचित फसलों का बीमा। राज्य की भागीदारी और अंतिम तारीख अलग हो सकती है।", "बैंक से मौसमी कर्ज़; ब्याज सहायता की शर्तें अलग हैं।"][index] ?? fallback,
  homeStateResume: (name) => `${name} के विकल्प देखें`,
  homeStateOutside: "इस पंजिका में हरियाणा की कुछ योजनाएँ हैं। बाकी राज्यों के लिए myScheme देखें।",
  homeReadScheme: "योजना पढ़ें →",
  homeSeasonEyebrow: "मौसम का उदाहरण · पंजिका की जाँच 26 सितंबर 2026",
  homeSeasonTitle: "रबी 2026–27 की तैयारी कर रहे हैं?",
  homeSeasonPanelBody: "पीएमएफबीवाई की अंतिम तारीख राज्य, फसल और मौसम की अधिसूचना पर निर्भर करती है। यह पंजिका आवेदन खुला होने की पुष्टि नहीं करती; तारीख पर भरोसा करने से पहले आधिकारिक सूचना देखें।",
  homeSeasonLink: "फसल बीमा की जानकारी",
  homeBrowseHint: "पंजिका में जाने का आसान रास्ता",
  homeHaryanaTitle: "हरियाणा की योजनाएँ खोज रहे हैं?",
  homeHaryanaBody: "फसल पंजीकरण, बागवानी, सिंचाई, पशुपालन, डेयरी और अन्य चुनिंदा राज्य कार्यक्रम देखें। हर योजना का आवेदन मार्ग और वर्तमान सूचना अलग है।",
  homeFeaturedEyebrow: "चुने हुए केंद्रीय कार्यक्रम",
  homeTrustTitle: "स्वतंत्र पंजिका",
  homeTrustBody: "किसान पत्र सरकारी वेबसाइट नहीं है। हर पन्ने पर दिए आधिकारिक स्रोत से पात्रता, तारीख और शुल्क की पुष्टि करें।",
  homeContinueEyebrow: "जहाँ छोड़ा था, वहीं से",
  homeContinueTitle: "आगे देखना जारी रखें",
  homeDeviceOnly: "सिर्फ़ इसी डिवाइस पर सहेजा · खाता ज़रूरी नहीं",
  homeSaved: "सहेजी योजनाएँ",
  homeRecent: "हाल में देखी योजनाएँ",
  homeClearSaved: "सहेजी सूची मिटाएँ",
  savedPageTitle: "आपकी सहेजी योजनाएँ",
  savedPageBody: "सहेजी सूची और हाल के पन्ने इसी डिवाइस के इस ब्राउज़र में रहते हैं। वे किसी खाते से जुड़कर सिंक नहीं होते।",
  savedEmpty: "अभी कोई योजना सहेजी नहीं है। योजना खोलें और उसे यहाँ रखने के लिए सहेजें चुनें।",
  savedRemove: "हटाएँ",
  homeFit: "देखें क्या मेरे काम की है",
  homeBrowse: "पूरी पंजिका देखें",
  homeStart: "इन तीन से शुरुआत करें",
  homeOwn: "ज़मीन अपने नाम है?",
  homeOwnBody:
    "पीएम-किसान साल में ₹6,000 तीन किस्तों में देता है, अगर ज़मीन का रिकॉर्ड परिवार के नाम हो।",
  homeSeason: "मौसम की चिंता है?",
  homeSeasonBody:
    "पीएमएफबीवाई में आपका प्रीमियम सीमित है। आपका राज्य उस मौसम में शामिल हो, और अंतिम तारीख से पहले नाम लिखवाना ज़रूरी है।",
  homeSeed: "बीज के लिए पैसा चाहिए?",
  homeSeedBody:
    "कर्ज़ किसान क्रेडिट कार्ड पर मिलता है। ब्याज में छूट उसी पर लगती है। समय पर चुकाने की तारीख बैंक से पूछ लें।",
  statMinistry: "योजनाएँ, मंत्रालय की संसदीय सूची में",
  statAllied: "अतिरिक्त केंद्रीय कार्यक्रम",
  statPlace: "जगह, जहाँ पात्रता, कागज़ और आधिकारिक लिंक एक साथ हैं",
  homeByWork: "काम के हिसाब से",
  schemeCount: (count) => (count === 1 ? "1 योजना" : `${count} योजनाएँ`),
  homeFeatured: "ज़्यादातर लोग पहले इन्हें देखते हैं",
  homeFeaturedBody:
    "इनमें खुद आवेदन होता है और रकम जाँची जा सकती है। हरियाणा की अपनी योजनाएँ पंजिका में हैं। बाकी राज्य अभी जोड़े नहीं गए।",
  searchLabel: "योजना खोजें",
  searchPlaceholder: "पीएम-किसान, ड्रिप, शहद, पेंशन, सोलर पंप",
  searchButton: "खोजें",
  registerEyebrow: (count) => `${count} प्रविष्टियाँ`,
  registerTitle: "पंजिका",
  registerLead:
    "योजना, फसल या ज़रूरत से खोजें। हर पन्ने पर लाभ, कौन आवेदन कर सकता है, कागज़ और आधिकारिक लिंक है।",
  all: "सभी",
  emptyTitle: "इस खोज से कुछ नहीं मिला।",
  emptyBody:
    "छोटा शब्द आज़माएँ — किसान, ड्रिप, शहद, पेंशन, मछली — या श्रेणी हटा दें।",
  emptyHaryana:
    "हरियाणा की सूची में यह नहीं मिला। पंजीकरण, धान, कपास आज़माएँ, या पूरा देश वाली सूची खोलें।",
  clearSearch: "खोज मिटाएँ",
  showing: (count, q) =>
    `${count} ${count === 1 ? "योजना" : "योजनाएँ"} दिख रही हैं${q ? ` — “${q}”` : ""}।`,
  listMinistry: "मंत्रालय की सूची",
  listAllied: "अतिरिक्त केंद्रीय कार्यक्रम",
  listPlatform: "ट्रेडिंग पोर्टल",
  crumbRegister: "पंजिका",
  openOfficial: (label) => `${label} खोलें`,
  catalogueReview: (date) => `पंजिका की प्रविष्टि ${date} को अपडेट की गई।`,
  sourceVerified: (date) => `आधिकारिक स्रोत की आख़िरी जाँच ${date} को हुई।`,
  sourceNotVerified: "इस पंजिका में आधिकारिक स्रोत की जाँच दर्ज नहीं है।",
  whatYouGet: "क्या मिलता है",
  whoCanApply: "कौन आवेदन कर सकता है",
  papers: "कौन से कागज़ रखें",
  howToApply: "आवेदन कैसे करें",
  beforePay: "किसी को पैसे देने से पहले",
  rateNote:
    "दर, फसल और राज्य की भागीदारी बदलती रहती है। आधिकारिक पन्ना ही मान्य है।",
  nearby: "इसी तरह की योजनाएँ",
  listNote: {
    "ministry-2026":
      "3 फरवरी 2026 को लोकसभा में रखी गई कृषि एवं किसान कल्याण मंत्रालय की सूची में नाम है।",
    allied:
      "3 फरवरी 2026 के उस अनुलग्नक से बाहर का अतिरिक्त केंद्रीय कार्यक्रम।",
    platform:
      "एकीकृत कृषि विपणन योजना के अंदर का ट्रेडिंग पोर्टल। किसान इसे नाम से खोजते हैं, इसलिए अलग दिया गया है।",
    state:
      "हरियाणा सरकार का कार्यक्रम। मौजूदा शर्तें और आवेदन अवधि आधिकारिक स्रोत पर जाँचें।",
  },
  finderEyebrow: "सूची सुझाव है, मंज़ूरी नहीं",
  finderTitle: "आपके खेत के लिए कौन सी योजना बन सकती है?",
  finderLead:
    "पहले अपना राज्य और काम चुनें। ज़मीन और उम्र की जानकारी देना वैकल्पिक है, इससे सूची और छोटी हो सकती है। यह सिर्फ़ सुझाव है; आधिकारिक सूचना में पात्रता और तारीख़ जाँचें।",
  stateLabel: "राज्य या केंद्र शासित प्रदेश",
  statePlaceholder: "राज्य चुनें",
  notSure: "पता नहीं",
  land: "ज़मीन",
  landOwner: "खेती की ज़मीन मेरे नाम है",
  landTenant: "मैं दूसरे की ज़मीन जोतता हूँ",
  landNone: "मैं खेत नहीं जोतता",
  landUnsure: "ज़मीन के रिकॉर्ड के बारे में पक्का नहीं हूँ",
  holding: "ज़मीन का रकबा",
  holdingSmall: "2 हेक्टेयर या उससे कम",
  holdingLarger: "2 हेक्टेयर से ज़्यादा",
  holdingUnsure: "रकबा पता नहीं",
  age: "उम्र",
  ageUnder: "18 से कम",
  ageYoung: "18 से 40",
  ageMid: "41 से 59",
  ageOld: "60 या उससे ज़्यादा",
  shg: "मैं महिला स्वयं सहायता समूह में हूँ, या हमारा समूह योजना ढूँढ रहा है।",
  work: "आप क्या काम करते हैं?",
  workHint: "खाली छोड़ें तो वे योजनाएँ दिखेंगी जिनसे ज़्यादातर किसान परिवार शुरुआत करते हैं।",
  showSchemes: "योजनाएँ दिखाएँ",
  shortlistTitle: "आपकी छोटी सूची यहाँ आएगी।",
  shortlistBody:
    "सवाल भरें और योजनाएँ दिखाएँ दबाएँ। तीन ढेर मिलेंगे: खुद आवेदन, समूह से, और राज्य दफ़्तर से।",
  noneTitle: "पंजिका में कोई मेल नहीं बैठा।",
  noneBody:
    "ऐसा तब होता है जब वह काम दूसरे राज्य तक सीमित हो, या ज़मीन के मालिकाना हक़ की शर्त पूरी न हो। पूरी पंजिका देखें, या जवाब बदलें।",
  openRegister: "पूरी पंजिका खोलें",
  mayFit: (count) =>
    `${count} योजनाएँ बन सकती हैं। आवेदन से पहले पन्ना पढ़ें। मेल का मतलब हक नहीं है।`,
  bandApply: "खुद आवेदन करें",
  bandApplyEmpty: "व्यक्तिगत आवेदन अलग से नहीं दिखा। समूह और राज्य वाले ढेर देखें।",
  bandGroup: "समूह या कारोबार के ज़रिए",
  bandGroupEmpty: "आपके चुने काम से कोई समूह योजना नहीं मिली।",
  bandState: "राज्य कृषि दफ़्तर से पूछें",
  bandStateEmpty: "कोई राज्य-संचालित योजना नहीं मिली।",
  aboutEyebrow: "यह पंजिका कैसे पढ़ें",
  aboutTitle: "स्रोत",
  aboutLead:
    "योजना का पन्ना एक ब्रीफिंग है, ताकि बैंक या कॉमन सर्विस सेंटर में आप जानें क्या पूछना है। यह दिशा-निर्देश नहीं है, और यह वादा नहीं कि पैसा मिलेगा।",
  primaryPages: "मुख्य पन्ने",
  links: {
    pib: "लोकसभा का जवाब, 3 फरवरी 2026, कृषि योजनाओं की सूची",
    ministry: "कृषि एवं किसान कल्याण विभाग",
    pmkisan: "पीएम-किसान",
    pmfby: "प्रधानमंत्री फसल बीमा योजना",
    cabinet: "ब्याज सहायता योजना को जारी रखने का कैबिनेट फैसला, 28 मई 2025",
    haryana: "मेरी फसल मेरा ब्योरा, हरियाणा का फसल पंजीकरण",
    myscheme: "myScheme, जिन राज्यों की सूची यहाँ अभी नहीं है",
  },
  missingEyebrow: "पन्ना नहीं मिला",
  missingTitle: "यह पन्ना पंजिका में नहीं है।",
  missingBody:
    "योजना का नाम बदला हो सकता है, या पता ग़लत है। जिस नाम से जानते हैं, उससे खोजें।",
  missingBack: "पंजिका पर वापस",
  reasons: {
    overlap: "यह आपके चुने हुए काम से मेल खाती है।",
    coreGeneral: "आम योजना है। खास योजनाओं के साथ इसे भी देख लें।",
    core: "ज़्यादातर किसान परिवारों को पहले यही देखनी चाहिए।",
    owner: "खेती की ज़मीन आपके नाम है, और यह योजना यही माँगती है।",
    cultivator: "आप फसल उगाते हैं। जहाँ योजना अनुमति दे, वहाँ बटाईदार भी आ सकता है।",
    unsureLand: "ज़मीन के रिकॉर्ड पर आप पक्के नहीं थे। आवेदन से पहले जाँच लें।",
    small: "आपका रकबा 2 हेक्टेयर के अंदर है, जो इस पेंशन के लिए ज़रूरी है।",
    age: "आपकी उम्र जुड़ने की सीमा के अंदर है।",
    ageUncertain: "आपकी उम्र की सीमा योजना की आयु सीमा से कुछ मेल खाती है। आवेदन से पहले अपनी सही उम्र जाँचें।",
    shg: "आप महिला स्वयं सहायता समूह में हैं, और योजना उन्हीं को चुनती है।",
    state: (name) => `यह ${name} में चलती है।`,
    group: "पैसा समूह या परियोजना को जाता है, व्यक्तिगत किस्त के रूप में नहीं।",
    startup: "यह कारोबार या प्रसंस्करण इकाई के लिए है, मौसमी फसल ऋण के लिए नहीं।",
    throughState: "इसे राज्य खोलता है। राष्ट्रीय पोर्टल पर निजी फ़ॉर्म न हो।",
    open: "आपके जवाब इसकी दी गई पात्रता से मेल खाते हैं; आवेदन की मौजूदा अवधि योजना के पन्ने पर जाँचें।",
  },
  placeLabel: "कौन सी सरकार",
  placeCentre: "पूरा देश",
  placeHaryana: "हरियाणा",
  placeLead:
    "पंजिका में केंद्र की योजनाएँ और हरियाणा के चुने हुए कार्यक्रम हैं। हरियाणा की प्रविष्टियों में कृषि, बागवानी, पशुपालन, डेयरी, मत्स्य, सिंचाई और किसानों की अन्य सहायता शामिल है। बाकी राज्य अभी नहीं जोड़े गए।",
  haryanaTitle: "हरियाणा की अपनी योजनाएँ",
  haryanaBody:
    "हरियाणा के कार्यक्रमों के आवेदन अलग-अलग तरीकों से होते हैं। कुछ में मेरी फसल मेरा ब्योरा पर पंजीकरण चाहिए; कुछ के लिए विभागीय पोर्टल, SARAL Haryana, बैंक या ज़िला दफ़्तर से संपर्क करना होता है। हर योजना की मौजूदा सूचना और अंतिम तारीख जाँचें।",
  haryanaLink: "हरियाणा की योजनाएँ खोलें",
  faqs: [
    {
      id: "official",
      q: "क्या यह सरकारी वेबसाइट है?",
      a: "नहीं। किसान पत्र एक स्वतंत्र पढ़ने की मेज़ है। आवेदन, भुगतान और सुधार केवल आधिकारिक पोर्टल पर होते हैं, या उस बैंक, मंडी या ज़िला दफ़्तर में जिसका नाम योजना पर लिखा है।",
    },
    {
      id: "list",
      q: "सूची कहाँ से आई?",
      a: "पंजिका में वे 28 कृषि योजनाएँ हैं जिन्हें कृषि एवं किसान कल्याण राज्य मंत्री ने 3 फरवरी 2026 को लोकसभा के लिखित उत्तर में सूचीबद्ध किया (पीआईबी विज्ञप्ति PRID 2222801), साथ में केंद्र के अन्य विभागों और हरियाणा के चुने हुए कार्यक्रम। यह किसानों से जुड़ी हर सरकारी योजना की पूरी सूची नहीं है। ई-नाम अलग दिखाया गया है क्योंकि किसान उसे अक्सर नाम से खोजते हैं।",
    },
    {
      id: "states",
      q: "राज्य की योजनाएँ कहाँ हैं?",
      a: "पंजिका में पहला राज्य हरियाणा है। यहाँ चुनी हुई प्रविष्टियों में फसल पंजीकरण और प्रोत्साहन, बागवानी, सिंचाई, पशुपालन और डेयरी, मत्स्य, तथा फसल नुकसान या दुर्घटना राहत शामिल हैं। हर कार्यक्रम की पात्रता और आवेदन मार्ग अलग है। बाकी राज्य अभी नहीं जोड़े गए; उनके लिए myScheme देखें और संबंधित राज्य विभाग से पुष्टि करें, क्योंकि कार्यक्रम और आवेदन अवधि बदलते रहते हैं।",
    },
    {
      id: "numbers",
      q: "क्या रुपए के आँकड़ों पर भरोसा करूँ?",
      a: "जाने-पहचाने आँकड़े सार्वजनिक स्रोत से जुड़े हैं: पीएम-किसान के ₹6,000, पीएमएफबीवाई की प्रीमियम सीमा, पीएम-केएमवाई की ₹3,000 पेंशन, 2025–26 तक जारी एमआईएसएस दर, फरवरी 2026 के उत्तर में एफपीओ की सीमा, नमो ड्रोन दीदी की सीमा, एग्रीश्योर का कोष, और पीएमएफएमई की 35% सीमा। मशीन और ड्रिप का प्रतिशत दिशा-निर्देश और राज्य की अतिरिक्त सहायता से बदलता है, इसलिए उन पन्नों पर पुराना आँकड़ा छापने के बजाय वर्तमान दर जाँचने को कहा गया है।",
    },
    {
      id: "miss",
      q: "ऋण पन्ने पर ₹3 लाख क्यों है, जब बजट में ₹5 लाख कहा गया?",
      a: "बजट 2025–26 में संशोधित ब्याज सहायता योजना की सीमा बढ़ाने की घोषणा हुई थी। 2025–26 के लिए केंद्रीय कैबिनेट की मंज़ूरी और उस वर्ष का रिज़र्व बैंक परिपत्र ब्याज लाभ को कुल ₹3 लाख पर रखता है, और केवल पशु, मछली या मधुमक्खी के ऋण पर ₹2 लाख। मंज़ूरी पत्र पर कौन सी सीमा है, बैंक से पूछें।",
    },
  ],
}

export const copy = { en, hi }

export function t(lang: Lang) {
  return copy[lang]
}

export function eyebrowClass(lang: Lang) {
  return lang === "hi"
    ? "text-xs font-medium text-clay"
    : "text-xs font-medium tracking-[0.16em] text-clay uppercase"
}
